<?php
/**
 * Copyright © 2018 Cointopay. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="block-content">
<div class="table-wrapper orders-recent">
<?php if($block->getOrder()) {?>
<table class="data table table-order-items recent" id="ctp-orders-table">
<caption class="table-caption">Recent Orders</caption>
<thead>
<tr>
<th scope="col" class="col id">Order #</th>
<th scope="col" class="col date">Date</th>
<th scope="col" class="col total">Order Total</th>
<th scope="col" class="col status">Status</th>
<th scope="col" class="col actions">Action</th>
</tr>
</thead>
<tbody>
<?php foreach($block->getOrder()->load() as $customerOrder) {?>
<tr>
<td data-th="Order #" class="col id"><?=$customerOrder['increment_id']?></td>
<td data-th="Date" class="col date"><?=$customerOrder['created_at']?></td>
<td data-th="Order Total" class="col total"><span class="price"><?=$customerOrder['grand_total']?></span></td>
<td data-th="Status" class="col status"><?=$customerOrder['status']?></td>
<td data-th="Actions" class="col actions">
<a href="javascript:void(0)" data-ctp="<?=$customerOrder['ext_order_id']?>" class="action view ctp_popup_btn">
<span>View Order</span>
</a>
</td>
</tr>
<?php }?>
</tbody>
</table>
</div>
<?php
}
if ($block->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
<?php else: ?>
    <div class="message info empty"><span><?= /* @escapeNotVerified */ __('You have no cointopay invoices.') ?></span></div>
<?php endif; ?>
<style type="text/css">
    .cointopay.popup-overlay{
        visibility:hidden;
        position: relative;
        background: #ffffff;
        width: 90%;
        z-index: 9;
    }
    .popup-overlay.active{
      visibility:visible;
      text-align:center;
    }
    .cointopay.popup-content {
      visibility:hidden;
    }
    .popup-content.active {
      visibility:visible;
    }
	.cointopay_details_main {
      display: flex;
	  flex-direction: row;
    }
    .cointopay_details {
      width: 80%;
    }
	.cointopay_details_qrcode {
      width: 18%;
    }
    .cointopay_details .remaining_amount {
      width: 100%;
      float: left;
      margin-top: 10px;
      text-align: left;
    }
    .cointopay_details .address {
      width: 100%;
      float: left;
      margin-top: 10px;
      text-align: left;
    }
    .cointopay_details .time {
      width: 100%;
      float: left;
      margin-top: 10px;
      text-align: left;
    }
    .cointopay_details .trxid {
      width: 100%;
      float: left;
      margin-top: 10px;
      text-align: left;
    }
    .cointopay_details .description {
      width:100%;
      text-align: left;
      margin-top: 6px;
      display: inline-block;
    }
    .cointopay.popup-overlay, .cointopay.popup-content {
    	z-index : 99999;
    	padding : 20px 0;
    	height : 50%;
    	top : 10%;
		margin: auto;
    }
	
	@media (min-width: 992px) {
		.modal-popup.ctp-popup .modal-inner-wrap {
			max-width: 900px;
		}
	}
</style>
<div id="ctp-modal-overlay" style="display:none;"></div>
<script type="text/javascript">
                require(
                    [
					'jquery',
					   'Magento_Ui/js/modal/modal'
					],
                    function($,modal) {
						 $(function() {
                        $(document).on('click', '.ctp_popup_btn', function() {
							    var ctpstr = '';
								var modaloption = {
						   type: 'popup',
						   modalClass: 'ctp-popup',
						   responsive: true,
						   innerScroll: true,
							title: false,
							buttons: [{
								text: $.mage.__('close'),
								class: '',
								click: function () {
									this.closeModal();
								}
							}],
							clickableOverlay: false
					   };
					   var callforoption = modal(modaloption, $('#ctp-modal-overlay'));
                                if ($('#ctp-modal-overlay').length) {
                                    selected_transaction_id = $(this).attr('data-ctp');
                                    $.ajax ({
                                        url: '<?php echo $block->getCoinsPaymentUrl() ?>ctpinfo/cointopay',
                                        showLoader: true,
                                        data: {selected_transaction_id:selected_transaction_id},
                                        type: "POST",
                                        success: function(result) {
											if (typeof result !== 'undefined') {
											//if (typeof result !== 'object') {
												//result = $.parseJSON(result);
											//}
											
											console.log(result);
											 $('#ctp-modal-overlay').html(result);
											 $("#ctp-modal-overlay").modal('openModal');
                                        }
										}
                                    });
                                }
                        });
                    });
				});
            </script>
</div>