<?php
/**
 * Copyright © 2018 Cointopay. All rights reserved.
 * See COPYING.txt for license details.
 */

$order = $block->getOrder();
$payment_gateway_code = $order->getPayment()->getMethodInstance()->getCode();
if ($payment_gateway_code == 'cointopay_gateway') {
    $escaper = $block->getobjectManager()->get(\Magento\Framework\Escaper::class);
    $curl = $block->getobjectManager()->create(\Magento\Framework\HTTP\Client\Curl::class);
    ?>
<style type="text/css">
    .cointopay.popup-overlay{
        visibility:hidden;
        position: relative;
        background: #ffffff;
        width: 90%;
        z-index: 9;
    }
    .popup-overlay.active{
      visibility:visible;
      text-align:center;
    }
    .cointopay.popup-content {
      visibility:hidden;
    }
    .popup-content.active {
      visibility:visible;
    }
    .cointopay_details_main {
      display: flex;
      flex-direction: row;
    }
    .cointopay_details {
      width: 80%;
    }
    .cointopay_details_qrcode {
      width: 18%;
    }
    .cointopay_details .remaining_amount {
      width: 100%;
      float: left;
      margin-top: 10px;
      text-align: left;
    }
    .cointopay_details .address {
      width: 100%;
      float: left;
      margin-top: 10px;
      text-align: left;
    }
    .cointopay_details .time {
      width: 100%;
      float: left;
      margin-top: 10px;
      text-align: left;
    }
    .cointopay_details .trxid {
      width: 100%;
      float: left;
      margin-top: 10px;
      text-align: left;
    }
    .cointopay_details .description {
      width:100%;
      text-align: left;
      margin-top: 6px;
      display: inline-block;
    }
    .cointopay.popup-overlay, .cointopay.popup-content {
        z-index : 99999;
        padding : 20px 0;
        height : 50%;
        top : 10%;
        margin: auto;
    }
    .checkout-success a.action.primary.continue{
        display:none;
    }
    @media (min-width: 992px) {
        .modal-popup.ctp-popup .modal-inner-wrap {
            max-width: 900px;
        }
    }
    @media only screen and (max-width: 767px) {
        .cointopay_details_main {
            display: block;
       }
       .cointopay.popup-overlay {
            padding: 15px !important;
        }
        .cointopay_details {
          width: 100%;
        }
        .cointopay_details_qrcode {
          width: 100%;
        }
        .cointopay_details p {
            text-align:center !important;
            font-size:11px !important;
        }
        .cointopay_details .address input {
            font-size:8.8px !important;
        }
        .modal-popup.ctp-popup .modal-content{
            padding-left: 1rem;
            padding-right: 1rem;
        }
        .modal-popup.modal-slide {
            width: 90%;
            right: 0;
            left: 0;
            margin: auto;
        }
        .modal-popup.ctp-popup .modal-footer {
            padding-bottom: 0;
            padding-top: 0;
            text-align: center;
        }
        .modal-popup.ctp-popup .modal-content {
            padding-bottom: 10px;
        }
        .cointopay.popup-content {
            padding: 0;
        }
        #ctp-modal-overlay > p {
            text-align:center !important;
        }
    }
</style>
<div class="checkout-success">
    <?php if ($order->getIncrementId()) {?>
        
        <!-- Cointopay popup Content -->
        <?php if ($payment_gateway_code == 'cointopay_gateway') { ?>
        <h1 style="margin-bottom: 20px;margin-top: 20px;">
        <a class="ctp_modal_open" href="javascript:void(0);">Show payment page</a>
        </h1>
            <?php $cointopay_content = $block->getCointopayHtml(); ?>
            <?php if ($cointopay_content) {?>
                    <p class="description"> 
                        <a target="_blank" href="<?=  $escaper->escapeUrl($cointopay_content->RedirectURL) ?>">
                            <?= $escaper->escapeHtml(__('View Invoice details on Cointopay.com')) ?>
                        </a>
                    </p>
            <?php }?>
        <div id="ctp-modal-overlay" style="display:none;">
         <p><?= $escaper->escapeHtml(__('Thank you for your order, please complete the payment below.')) ?></p>
            <?php
            if ($cointopay_content) {
                $viewfileurl = $block->getViewFileUrl('Cointopay_PaymentGateway::images/cointopay.gif');
                $confmsg = 'Please make the payment and wait for the success confirmation page.';
                $qrcodeurlCoin = 'https://quickchart.io/qr?size=300&text='.$cointopay_content->coinAddress;
                $urlCoin = 'https://quickchart.io/qr?size=300&text=' . urlencode($cointopay_content->coinAddress);
                $curl->get($urlCoin);
                ?>
                <div class="popup-overlay cointopay active">
                  <div class="popup-content cointopay active">    
                    <img src="<?= $escaper->escapeUrl($viewfileurl); ?>" />
                    <p class="description" style="text-align:center !important;">
                    <strong>
                    <?= $escaper->escapeHtml(__($confmsg)) ?>
                    </strong>
                    </p>
                    <h1> PAYMENT DETAILS </h1>
                    <div class="cointopay_details_main">
                        <div class="cointopay_details_qrcode">
                        <?php $qrcodeurl = $cointopay_content->QRCodeURL;?>
                            <img src="<?=$escaper->escapeUrl($qrcodeurl)?>" class="ctpQRcode" title="QR Code" />
                        <?php if ($curl->getStatus() === 200) { ?>
                            <img src="<?=$escaper->escapeUrl($urlCoin)?>" class="ctpCoinAdress" style="display:none;" />
                        <?php }?>
                        </div>
                        <div class="cointopay_details">
                            <p class="remaining_amount"><strong>Amount:</strong><br>
                                <?=  (float) $cointopay_content->Amount.' ' ?>
                                <?= $escaper->escapeHtml(strtoupper($cointopay_content->CoinName)).' ' ?>
                                <?php
                                    $coinctpurl = 'https://s3-eu-west-1.amazonaws.com/cointopay/img/';
                                    $ctpcoinurl = $coinctpurl.$cointopay_content->CoinName.'_dash2.png';
                                ?>
                                <img src="<?= $escaper->escapeUrl($ctpcoinurl) ?>" style="width:20px;" />
                                       (<?=  $escaper->escapeHtml($cointopay_content->ChainName).' ' ?> Network)
                            </p>
                            <?php if (property_exists($cointopay_content, 'Tag')) {
                                if (!empty($cointopay_content->Tag)) {
                                    ?>
                            <p class="description"><strong>Memo/Tag: </strong> 
                                    <?= $escaper->escapeHtml($cointopay_content->Tag) ?> 
                            </p>
                            <?php }}?>
                            <p class="address"><strong>Address: </strong> <br> 
                                <?php $ctpAd = $cointopay_content->coinAddress;?>
                                <input type="text" value="<?=$escaper->escapeHtml($ctpAd)?>" style="width:100%;" /> 
                            </p>
                            <p class="description">
                                <button class="btn btn-success btnCrypto mb-2">CRYPTO LINK</button>
                            </p>
                            <p class="time"><strong>Expiry: </strong> 
                                <span id="expire_time">
                                    <?php $ctpExpTime = strtotime("+".$cointopay_content->ExpiryTime." minutes");?>
                                    <?=$escaper->escapeHtml(date("m/d/Y h:i:s T", $ctpExpTime))?>
                                </span>
                            </p>
                            <p class="trxid"><strong>Transaction ID: </strong> 
                            <?= (string) $cointopay_content->TransactionID ?>
                            </p>
                            <p class="description">Make sure to send enough to cover  any coin transaction fees!</p>
                            <p class="description">Send an equal amount or more.</p>
                             <p class="description"> 
                                 <?php $ctpRedURL = $cointopay_content->RedirectURL;?>
                                 <a target="_blank" href="<?=$escaper->escapeUrl($ctpRedURL)?>">
                                    View Invoice details
                                 </a>
                             </p>
                            <?php $ctracID = $cointopay_content->TransactionID;?>
                            <input type="hidden" id="cointopay_trid" value="<?=(string) $ctracID?>" />
                        </div>
                    </div>
                  </div>
                </div>
            <script>
                require(
                    ['jquery'],
                    function($) {
                        $(function() {
                            interval = setInterval(function() {
                                if ($('#cointopay_trid').length) {
                                    selected_coin = $('#cointopay_trid').val();
                                    $.ajax ({
                                        url: '<?= $escaper->escapeUrl($block->getCoinsPaymentUrl()) ?>',
                                        //showLoader: true,
                                        data: {paymentaction:selected_coin, type:'status'},
                                        type: "POST",
                                        success: function(result) {
                                            if (result.status == 'paid') {
                                                $('.popup-content.cointopay').html('<h3>'+
                                                'Thank you, your payment is received!</h3>'+
                                                '<p class="description"> <a target="_blank" '+
                                                'href="<?=  $escaper->escapeUrl($cointopay_content->RedirectURL) ?>">'+
                                                'View Invoice details</a></p>');
                                            } else if (result.status == 'expired') {
                                                $('.popup-content.cointopay').html('<h3>Payment time expired!</h3>'+
                                                '<p class="description"> <a target="_blank" '+
                                                'href="<?=  $escaper->escapeUrl($cointopay_content->RedirectURL) ?>">'+
                                                'View Invoice details</a></p>');
                                            }
                                             else if (result.status == 'underpaid') {
                                                $('.popup-content.cointopay').html('<h3>'+
                                                'You have underpaid, please pay the '+
                                                'remaining amount or contact support!'+
                                                '</h3><p class="description"> <a target="_blank" '+
                                                'href="<?=  $escaper->escapeUrl($cointopay_content->RedirectURL) ?>">'+
                                                'View Invoice details</a></p>');
                                            }
                                        }
                                    });
                                }
                            }, 10000);
                            
                            // count down time left
                            var d1 = new Date (),
                            d2 = new Date ( d1 );
                            d2.setMinutes ( 
                                d1.getMinutes() + <?= $escaper->escapeHtml($cointopay_content->ExpiryTime) ?> 
                            );
                            var countDownDate = d2.getTime();

                            // Update the count down every 1 second
                            var x = setInterval(function() {
                                if ($('#expire_time').length) {
                                    // Get todays date and time
                                    var now = new Date().getTime();
                                    
                                    // Find the distance between now an the count down date
                                    var distance = countDownDate - now;
                                    
                                    // Time calculations for days, hours, minutes and seconds
                                    var days = Math.floor(distance / (1000 * 60 * 60 * 24));
                                    var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
                                    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
                                    var seconds = Math.floor((distance % (1000 * 60)) / 1000);
                                    
                                    // Output the result in an element with id="expire_time"
                                    document.getElementById("expire_time").innerHTML = days + "d " + hours + "h "
                                    + minutes + "m " + seconds + "s ";
                                    
                                    // If the count down is over, write some text 
                                    if (distance < 0) {
                                        clearInterval(x);
                                        document.getElementById("expire_time").innerHTML = "EXPIRED";
                                    }
                                }
                            }, 1000);
                        });
                    });
            </script>
            <?php } else {
                        echo "No Cointopay data found due to empty session values";
            }
            ?>
            </div>
            <script>
               require(
                   [
                       'jquery',
                       'Magento_Ui/js/modal/modal'
                   ],
                   function (
                       $,
                       modal
                   ) {
                       var modaloption = {
                           type: 'popup',
                           modalClass: 'ctp-popup',
                           responsive: true,
                           innerScroll: true,
                            title: false,
                            buttons: [{
                                text: $.mage.__('close'),
                                class: '',
                                click: function () {
                                    this.closeModal();
                                }
                            }],
                            clickableOverlay: false
                       };
                       var callforoption = modal(modaloption, $('#ctp-modal-overlay'));
                       $('#ctp-modal-overlay').modal('openModal');
                   }
               );
            </script>
            <script>
                require(
                    ['jquery'],
                    function($) {
                        $(function() {
                            $('.ctp_modal_open').click(function(){
                                //$('#ctp-modal-overlay').css("display", "block");
                                // var modalContainer = 
                                 $("#ctp-modal-overlay").modal('openModal');
                                //modalContainer.modal('openModal');
                            });
                            if ($('.btnCrypto').length) {
                                $('.btnCrypto').click(function(){
                                    if ($(this).text() == 'CRYPTO LINK') {
                                        $(this).text('CRYPTO ADDRESS');
                                        $('.ctpQRcode').hide();
                                        $('.ctpCoinAdress').show();
                                    } else if ($(this).text() == 'CRYPTO ADDRESS') {
                                        $(this).text('CRYPTO LINK');
                                        $('.ctpCoinAdress').hide();
                                        $('.ctpQRcode').show();
                                    }
                                    
                                });
                            }
                        });
                    });
            </script>
        <?php } ?>
    <?php } ?>
    <a class="action primary ctp" style="float: right;" href="<?=$escaper->escapeHtml($block->getBaseUrl())?>">
        Continue Shopping
    </a>
</div>
<?php }?>
